tinyMCEPopup.requireLangPack();

var ContentAssociationDialog = {
    
	init : function() {
		var f = document.forms[0];
        
        var callbacks = {
            
            success : function(data) {
                var content_items = jQuery.parseJSON(data);
                var optionsHTML = new Array();
                for(var i = 0; i < content_items.length; i++ ) {
                    optionsHTML.push('<option value="' + content_items[i].model + '-' + content_items[i].id + '">' + content_items[i].name + '</option>');
                }            
                $('#content-items').html(optionsHTML.join(''));
            },
            
            error : function(data) {
                
            }
        }
            
        $.ajax({url : '/content-association/content_items.json', success : callbacks.success, error : callbacks.error});
       
	},

	insert : function() {
		// Insert/Edit the contents from the input into the document
		var ed = tinyMCEPopup.editor;
		var selectedNode = ed.selection.getNode();
        var selectedContentItem = $('#content-items :selected').val();
        var sourceItem = tinyMCEPopup.getWin().document.getElementById('model_name').value + '-' + tinyMCEPopup.getWin().document.getElementById('model_id').value;
        // selectedNode.name should be the UUID generated by the API. 
        var data = {item : selectedContentItem, source_item : sourceItem, model_field : ed.id, link_name : ($(selectedNode).attr('name') == undefined ? '' : $(selectedNode).attr('name'))}
		var callbacks = {
            
            success : function(data) {
                var content_association = jQuery.parseJSON(data);
                // Update the link with the data coming from the API.
                if(selectedNode.nodeName != 'A') { // New link.
        		    ed.execCommand('mceInsertContent', false, '<a name="' + content_association.target_model_link_name + '" href="' + content_association.target_model_link + '" rel="contentassociation">' + tinyMCEPopup.editor.selection.getContent({format : 'text'}) + '</a>');
        		} else { // Editing a link.
        		    ed.dom.setAttrib(selectedNode, 'href', content_association.target_model_link);
        		    
        		}
        		tinyMCEPopup.close();
            },
            
            error : function(data) {
                alert('Problem with content association.');
            }
        }
         
        $.ajax({url : '/content-association/content_items.json', type : 'POST', data : data, success : callbacks.success, error : callbacks.error});
        
	}
};

tinyMCEPopup.onInit.add(ContentAssociationDialog.init, ContentAssociationDialog);
